version: '2'

services:
  wb-container:
    image: "srp33/wishbuilder-cli"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Analysis/GeneyWishBuilder/WishBuilder-CLI:/app
    user: '1004:1004'
    environment:
      - PYTHONPATH=/app/ShapeShifter/ShapeShifter
    command: python3 WishBuilder.py
